#
# Mögliche Permissions:
#
#  create_comment       - Lob/Hinweis/Kritik anlegen /requests/comments/create
#  read_comment_author  - Lob/Hinweis/Kritik - Ersteller Email lesen
#  create_notes         - interne Kommentare anlegen /requests/notes/create
#  read_notes           - interne Kommentare lesen /requests/notes/index
#  create_request       - Neuen Vorgang anlegen /requests/create
#

<API-Key>:
  name: <Client-Name>
  permissions:
    - create_comments
    - read_comment_author
    - create_notes
    - read_notes
    - create_request
