constants:
  jurisdiction_id: rostock.de

  geocoder_url: https://geo.sv.rostock.de/api/geokodierung
  ks_backend_service_url: http://localhost:8015/backend/service/
  ks_images_url: http://klarschiff-test/hgw/fotos/

  image_max_height: 720
  image_max_width: 720

  memcache_server_url: localhost:11211
  memcache_server_namespace: klarschiff

  discovery_changeset: 2015-11-05 08:43
  discovery_contact: "Hanse- und Universitätsstadt Rostock, Kataster-, Vermessungs- und Liegenschaftsamt, Holbeinplatz 14, 18069 Rostock, Telefon: +49 381 381-6281, Telefax: +49 381 381-6902, E-Mail: klarschiff.hro@rostock.de"
  discovery_key_service: klarschiff.hro@rostock.de
  discovery_endpoints:
    -
      specification: http://wiki.open311.org/GeoReport_v2
      url: https://geo.sv.rostock.de/citysdk
      changeset: 2015-11-05 08:43
      type: production
      formats:
        - application/json
        - text/xml
    -
      specification: http://wiki.open311.org/GeoReport_v2
      url: https://support.klarschiff-hro.de/citysdk
      changeset: 2015-11-05 08:43
      type: test
      formats:
        - application/json
        - text/xml
    -
      specification: http://wiki.open311.org/GeoReport_v2
      url: https://demo.klarschiff-hro.de/citysdk
      changeset: 2015-11-05 08:43
      type: test
      formats:
        - application/json
        - text/xml
